sudo: required
services:
  - docker

before_install:
  - docker build -t alumedot/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alumedot/react-test npm test

after_success:
  - docker build -t alumedot/multi-client ./client
  - docker build -t alumedot/multi-nginx ./nginx
  - docker build -t alumedot/multi-server ./server
  - docker build -t alumedot/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push alumedot/multi-client
  - docker push alumedot/multi-nginx
  - docker push alumedot/multi-server
  - docker push alumedot/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-657436330303
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
